version: "3.8"

services:
  csv-management-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:5000/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1))",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  uploads:
    driver: local
